import { Injectable } from '@nestjs/common';
// eslint-disable-next-line @nx/enforce-module-boundaries
import { Prisma } from '../generated/prisma';
import { PrismaService } from '../prisma/prisma.service';
import { CreateOrderDto } from './dto/create-order.dto';

const orderInclude = {
  items: true,
} satisfies Prisma.OrderInclude;

export type OrderWithItems = Prisma.OrderGetPayload<{ include: typeof orderInclude }>;

@Injectable()
export class OrdersRepository {
  constructor(private readonly prisma: PrismaService) {}

  findById(id: string): Promise<OrderWithItems | null> {
    return this.prisma.order.findUnique({ where: { id }, include: orderInclude });
  }

  findByUser(userId: string, page: number, limit: number) {
    const skip = (page - 1) * limit;
    return Promise.all([
      this.prisma.order.findMany({
        where: { userId },
        include: orderInclude,
        orderBy: { createdAt: 'desc' },
        skip,
        take: limit,
      }),
      this.prisma.order.count({ where: { userId } }),
    ]);
  }

  findByIdempotencyKey(key: string) {
    return this.prisma.idempotencyKey.findUnique({
      where: { key },
      include: { order: { include: orderInclude } },
    });
  }

  findSnapshotsByIds(productIds: string[]) {
    return this.prisma.productSnapshot.findMany({
      where: { productId: { in: productIds } },
    });
  }

  /**
   * Creates order + idempotency key + two outbox events (created + confirmed) atomically.
   * orderId is pre-generated by the caller so events can be built before insertion.
   */
  createAndConfirmOrder(
    orderId: string,
    dto: CreateOrderDto,
    userId: string,
    snapshots: { productId: string; name: string; price: Prisma.Decimal; currency: string }[],
    outboxEvents: { routingKey: string; payload: object }[],
  ): Promise<OrderWithItems> {
    const snapshotMap = new Map(snapshots.map((s) => [s.productId, s]));
    const totalAmount = dto.items.reduce((sum, item) => {
      const snap = snapshotMap.get(item.productId)!;
      return sum.add(snap.price.mul(item.quantity));
    }, new Prisma.Decimal(0));

    const currency = snapshots[0]?.currency ?? 'USD';

    return this.prisma.$transaction(async (tx) => {
      await tx.order.create({
        data: {
          id: orderId,
          userId,
          status: 'CONFIRMED',
          totalAmount,
          currency,
          items: {
            create: dto.items.map((item) => {
              const snap = snapshotMap.get(item.productId)!;
              return {
                productId: item.productId,
                productName: snap.name,
                unitPrice: snap.price,
                quantity: item.quantity,
              };
            }),
          },
          idempotencyKey: { create: { key: dto.idempotencyKey } },
        },
      });

      for (const event of outboxEvents) {
        await tx.outbox.create({
          data: { routingKey: event.routingKey, payload: event.payload as Prisma.InputJsonValue },
        });
      }

      return tx.order.findUniqueOrThrow({ where: { id: orderId }, include: orderInclude });
    });
  }

  cancelOrder(
    id: string,
    outboxEvent: { routingKey: string; payload: object },
  ): Promise<OrderWithItems> {
    return this.prisma.$transaction(async (tx) => {
      const order = await tx.order.update({
        where: { id },
        data: { status: 'CANCELLED' },
        include: orderInclude,
      });

      await tx.outbox.create({
        data: {
          routingKey: outboxEvent.routingKey,
          payload: outboxEvent.payload as Prisma.InputJsonValue,
        },
      });

      return order;
    });
  }

  upsertProductSnapshot(data: {
    productId: string;
    name: string;
    price: string;
    currency: string;
    stockView?: number;
  }) {
    return this.prisma.productSnapshot.upsert({
      where: { productId: data.productId },
      update: {
        name: data.name,
        price: new Prisma.Decimal(data.price),
        currency: data.currency,
        ...(data.stockView !== undefined && { stockView: data.stockView }),
      },
      create: {
        productId: data.productId,
        name: data.name,
        price: new Prisma.Decimal(data.price),
        currency: data.currency,
        stockView: data.stockView ?? 0,
      },
    });
  }

  updateSnapshotStock(productId: string, newQty: number) {
    return this.prisma.productSnapshot.updateMany({
      where: { productId },
      data: { stockView: newQty },
    });
  }

  isEventProcessed(eventId: string) {
    return this.prisma.processedEvent.findUnique({ where: { eventId } });
  }

  markEventProcessed(eventId: string) {
    return this.prisma.processedEvent.create({ data: { eventId } });
  }
}
